### PR TITLE
ssh: add support for extension negotiation (rfc 8308)

### PR DESCRIPTION
**Pull request by drakkan**
This is a rebase of the following PR

https://github.com/golang/crypto/pull/197

with some changes and improvements:

- added support for client certificate authentication
- removed read loop from server handshake
- adapted extInfoMsg to upstream changes

Signed-off-by: Nicola Murino <nicola.murino@gmail.com>

### CODE REVIEW

**Comment by r0mant** [comment]
Hello, is there any ETA on when this PR will merge? Thanks.

**Comment by ianlancetaylor** [comment]
@r0mant Please don’t reply on this GitHub thread. Visit golang.org/cl/396714.  Thanks.

**Comment by reedloden** [comment]
@drakkan Did this get addressed upstream?

**Comment by brodock** [comment]
@reedloden doesn't seem like.

**Comment by stanhu** [comment]
Actually, it did. https://go.dev/cl/447757 was merged in November 2022 and pared down this pull request: https://github.com/golang/go/issues/49269#issuecomment-1302661997. 

I don't think we need to support `ext-info-s` either since this causes the client to send `SSH_MSG_EXT_INFO`, and this pull request just read and threw away the message.

**Pull request closed without merging**
