### PR TITLE
Adding RC6 cipher to supplemental crypto tools

### PR DESCRIPTION
**Pull request by CampNowhere**

### CODE REVIEW

**Comment by bradfitz** [comment]
@googlebot, ping.

**Comment by dgryski** [comment]
Also https://github.com/dgryski/go-rc6 . However, given the lack of use of RC6 outside of the NSA, it's not clear this needs to be in /x/crypto.  There are lots of crypto algorithms (my GitHub is full of them).  I don't think they all need to be added to the extended repositories.

**Comment by bradfitz** [comment]
@agl, do you have preferences one way or another?

**Comment by FiloSottile** [comment]
We also have https://golang.org/cl/73032 but I'm just as skeptical that we need to maintain this in x/crypto.

As a meta comment, aren't we supposed not to comment on GitHub PRs, per https://golang.org/wiki/GerritBot?

**Comment by bradfitz** [comment]
> As a meta comment, aren't we supposed not to comment on GitHub PRs, per https://golang.org/wiki/GerritBot?

Yeah. But it looks like an issue to me (I'm not used to seeing pull requests), and we tend to have discussions on GitHub [issues] rather than Gerrit. So I got confused. @andybons, maybe the bot should be stricter? Dunno.

**Comment by andybons** [comment]
We could restrict comments to owners. :man_shrugging: lots to think about how to deal with the mental models

**Comment by CampNowhere** [comment]
I was simply trying to contribute and follow the procedure for contributing :-( I saw some feedback in my code and it looks like I just need to make a couple of formatting corrections.

As to "why should we add this", I don't know what the criteria are by which these things are decided. I like the Go language, how am I supposed to know what would be meaningful or valued to contribute?

**Comment by FiloSottile** [comment]
@CampNowhere Sorry if the feedback sounded harsh, it was not meant to be! This PR was reopened because we now support GitHub PRs and had initially not noticed you had opened a CL on Gerrit over at https://golang.org/cl/73032. Thanks for following that process.

We are happy about all contributions, what I mentioned on Gerrit is that we use the [change proposal process](https://golang.org/s/proposal-process) to make decisions on things like new packages. You would just [open a new issue](https://github.com/golang/go/issues/new) (no need to fill in the bug report template) with a title like `proposal: x/crypto/rc6: new package` and a link to your CL. Feel free to also ping me and agl. We'll take it from there.

You can help us make a decision by explaining in what programs you could have used this package, or what protocols use RC6. We have a high bar for what we add to the repos because of the ongoing maintenance cost, and in the context of crypto to avoid overwhelming users with options.

Thanks again for contributing!

**Comment by bradfitz** [comment]
@CampNowhere, I think the trap you fell into was sending new code without a discussion (e.g. via a proposal). See https://golang.org/doc/contribute.html#Design

And see also https://golang.org/doc/faq#x_in_std

In general, fixing bugs in Go is easier contribution-wise than adding new code. Adding new code requires a lot more discussion.

But like @FiloSottile said, don't be discouraged. We do welcome contributions and love to see new faces join the project.

**Pull request closed without merging**
