### PR TITLE
ssh: make 'NoAuthError' be a var instead of a type

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by leonklingele** [comment]
fyi @hanwen 
Don't know why it's still exported, but alas.

**Comment by andybons** [comment]
Editing to remove the Change-Id. Was this due to the standard Gerrit commit hook? Filed https://github.com/golang/go/issues/23931 to fix.

**Comment by leonklingele** [comment]
@andybons yeah, probably. I've used Gerrit before and the pre-commit hook is still installed.

**Comment by andybons** [comment]
This PR (HEAD: cba2c97d628fb9723ea590afa8732b0261078fb0) has been imported to Gerrit for code review.

Please visit https://go-review.googlesource.com/#/c/crypto/+/95155 to see it.

Tip: You can toggle comments from me using the `comments` slash command (e.g. `/comments off`)
See the [Wiki page](https://golang.org/wiki/GerritBot) for more info

**Comment by leonklingele** [comment]
> Patch Set 1: (2 comments)

@andybons is this a bug of little @gopherbot?

**Comment by andybons** [comment]
@leonklingele no this is intended behavior.

**Comment by leonklingele** [comment]
Seems to have been merged already.

**Pull request closed without merging**
