### PR TITLE
fixed test printout

### PR DESCRIPTION
**Pull request by awalterschulze**

### CODE REVIEW

**Comment by dsymonds** [comment]
The Go project doesn't use GitHub pull requests. We use Gerrit for code review. See https://golang.org/doc/contribute.html.

Please re-send this using Gerrit. Thanks!

**Comment by awalterschulze** [comment]
That is way to much effort.
I'll just change it on my subtree.
Please reconsider using github pull requests.
There is a reason why the community on github is thriving and it is pull
requests.
Otherwise I have no idea why you made the move in the first place.

**Comment by bradfitz** [comment]
We've considered Github pull requests many times, and communicated our problems with Github's code review offerings with many people, in many places, including in person with Github at their offices and with Github employees elsewhere. They're very well aware that their code review tools suck, and they're working on it.

If you're not willing to upload your change for review with Gerrit, it must not be very important.

**Comment by awalterschulze** [comment]
Why do their code review tools "suck", maybe you have a link you can point
me to so you don't have to communicate it again.

**Comment by bradfitz** [comment]
The most comprehensive and succinct summary of the issues I've seen written publicly was just covered by @adg at the London Go Gathering. The videos should be up any day now (Andrew?), so I'll link them here when they're up.

**Comment by minux** [comment]
Andrew listed several problems of the pull request on this slide:
http://go-talks.appspot.com/github.com/golang/talks/2015/state-of-go.slide#7

@adg, it seems we need to redeploy the talks.golang.org app, the state of Go
talk is not shown atm.

**Comment by adg** [comment]
@bradfitz the videos should be up mid-week next week.

@minux I just re-deployed talks. The slides are at https://talks.golang.org/2015/state-of-go.slide#7

@awalterschulze in short, GitHub's PRs make it hard to pay attention to the fine details of code changes.  We spend all day reviewing each others code, and PRs don't suit the way we work.

A lot of people have contributed using Gerrit and they seem to do ok. You should check it out!

**Comment by bradfitz** [comment]
@awalterschulze might be right that Github PRs are better for trivial changes like this one. But they don't work for large, week+ reviews with dozens of revisions and comments from many people.

**Comment by awalterschulze** [comment]
*When in Rome.*

The only extreme complaint that I can see is:
Cannot compare differences between patch sets.
Maybe you can get github to add this to their github desktop gui.

I have tried contributing with your workflow before.
It was tedious and in the end my patch was not accepted, so I am a bit
biased, but still.
In then end I opted to rather just report issues, since it does not require
a huge context switch and you guys do a great job of getting it fixed :)
In this case on github it was actually easier to make a pull request than
report an issue, since their is no ambiguity in my description of the issue.

For you working on go a lot of the time you are used to the workflow.
So it does not really matter that much what it is, as long it is consistent.
If its consistent it does not require a context switch and you are in a
comfort zone.
Thats great and everything, but

For contributors the story is different.
I first have to read your contribution guidelines again, because they are
way too long to remember.
Then I have to:

Introduction <https://golang.org/doc/contribute.html#Introduction>Discuss
your design <https://golang.org/doc/contribute.html#Design>Testing redux
<https://golang.org/doc/contribute.html#Testing>Code review
<https://golang.org/doc/contribute.html#Code_review>Set up authentication
for code review <https://golang.org/doc/contribute.html#tmp_4>Register with
Gerrit <https://golang.org/doc/contribute.html#tmp_5>Install the
git-codereview command <https://golang.org/doc/contribute.html#tmp_6>Set up
git aliases <https://golang.org/doc/contribute.html#tmp_7>Understanding the
git-codereview command <https://golang.org/doc/contribute.html#tmp_8>Switch
to the master branch <https://golang.org/doc/contribute.html#tmp_9>Make a
change <https://golang.org/doc/contribute.html#tmp_10>
Mail the change for review
<https://golang.org/doc/contribute.html#tmp_11>Reviewing
code <https://golang.org/doc/contribute.html#tmp_12>Revise and upload
<https://golang.org/doc/contribute.html#tmp_13>Synchronize your client
<https://golang.org/doc/contribute.html#tmp_14>Reviewing code by others
<https://golang.org/doc/contribute.html#tmp_15>Submit the change after the
review <https://golang.org/doc/contribute.html#tmp_16>More information
<https://golang.org/doc/contribute.html#tmp_17>Copyright
<https://golang.org/doc/contribute.html#copyright>

On github I just create a pull request
git clone
make the change
<typically here is one more step>
git push
make the pull request

This is why github and bitbucket are more popular than code.google.com
Its not just an git repo.
Its a GUI for git workflow.
You knew this coming into the github community.
The github community is only this popular because of the pull requests and
then the community snowballed.

Maybe you should not have given up on code.google.com
Implement a pull request gui the way you want it and you are done.
Git is already available on code.google.com, I have been using it for years.
I don't understand what feature you are using here if you are not using
pull requests?

When in Rome.

Mic drop

**Comment by kargakis** [comment]
```
I don't understand what feature you are using here if you are not using pull requests?
```

@awalterschulze https://talks.golang.org/2015/state-of-go.slide#4

**Comment by awalterschulze** [comment]
These are the only points that are about github and not just about git:
- Puts us closer to our community.
- Other GitHub repos can more easily link to Go issues and commits.
- and mabye Automated CLA checking.
What else is not just about using git instead of mecurial?
Am I missing something?

**Comment by kargakis** [comment]
```
Why Git?

    Gerrit and GitHub use Git.

 Why Gerrit?

    Rietveld was unmaintained.
    Gerrit is actively maintained; used by Android and Chrome, among others.

Why GitHub?

    Puts us closer to our community.
    Other GitHub repos can more easily link to Go issues and commits.
```

**Comment by kargakis** [comment]
Also, note to the Go developers:
```
Accepting a patch creates a "merge commit" (ugly repo history).
```
This can be worked around but not through Github's UI.
https://github.com/GoogleCloudPlatform/kubernetes/issues/4251
btcd (alt full-node btc client) devs follow this workflow
https://github.com/btcsuite/btcd

**Comment by minux** [comment]
The main problem of pull requests is the code review system is not good
enough for all but the smallest changes.

**Comment by ianlancetaylor** [comment]
If you really want to discuss this, plesae take it to the golang-nuts mailing list, not a random pull request.

But, fair warning: it's not going to change.  Even if we ignore everything else, which we won't, automatic CLA checking is a must-have feature for us.

**Pull request closed without merging**
