### PR TITLE
chacha20: add SetCounter method

### PR DESCRIPTION
**Pull request by lukechampine**
Fixes golang/go#35506

### CODE REVIEW

**Comment by lukechampine** [comment]
It's not clear to me whether this should take a `uint32` or a `uint64`. In the [reference implementation](https://cr.yp.to/streamciphers/timings/estreambench/submissions/salsa20/chacha8/ref/chacha.c), the nonce and counter are both 64 bits:
```c
    x->input[12] = PLUSONE(x->input[12]);
    if (!x->input[12]) {
      x->input[13] = PLUSONE(x->input[13]);
      /* stopping at 2^70 bytes per nonce is user's responsibility */
    }
```
(2^70 = 2^64 * 64-byte blocks)

However, when we use a 12-byte nonce, we're essentially stealing 4 bytes from the counter, so the counter becomes a `uint32`, and if an overflow would occur, we panic.

As for XChaCha, though, the nonce is back to 8 bytes, and the draft says that the other 4 bytes should be zeroed. This leaves it somewhat ambiguous as to whether those bytes should be used for the counter or not.

cc @aead because his implementation also deals with this question; specifically, it takes a `uint64`, but truncates it if the nonce is 12 bytes. Notably, the nonce is *not* truncated when using XChaCha.

**Comment by aead** [comment]
The reason behind using a 32 bit counter for ChaCha and a 64 bit counter for XChaCha is simply that it's possible to use 64 bit counters with XChaCha (and therefore, generate longer key streams).

For any real-world application a 32 bit counter should be sufficient b/c `2^32 * 64 = 256 GiB`. As mentioned above, using a 64 bit counter for ChaCha would modify the nonce-part of the internal state, and therefore, may cause security issues (nonce reuse). Using a 64 bit counter for XChaCha is okay from a security perspective since the nonce-part of the internal state is only 8 byte (compared to 12 bytes in case of ChaCha). It's up to you whether you consider the 4 bytes in the state as part of the counter or part of the nonce.

However, if we would accept a 64 bit counter the following code would either panic depending on the `cipher.Stream` type:
```
type counter interface {
     SetCounter(c uint64)
}

type stream struct {
     c cipher.Stream
     pos int64
}

func (s *stream) Skip(n int) {
     if c, ok := s.c.(counter); ok {
           // use SetCounter and io.CopyN
           // will panic if `pos + n` overflows 2^32 in case of ChaCha
     } else {
           // use io.CopyN
     }
}
```

I would favor an API that is "safe" in "all" scenarios compared to the more flexible API that also covers a very small fraction of use cases, and therefore, the `32 bit counter`.

**Comment by rod-hynes** [comment]
Hi. In https://github.com/lukechampine/crypto/tree/eef4af8e43ea2189280146254263a2a94f4298b2 we have encountered a panic in what we believe to be a valid input case:

```
func TestIETFQUICHeaderProtection(t *testing.T) {

	var key [32]byte
	var nonce [12]byte
	var block [64]byte

	// IETF ChaCha20 allows 2^32 blocks:
	// https://tools.ietf.org/html/rfc7539#section-2.3.2.
	//
	// IETF QUIC ChaCha20-based header protection,
	// https://tools.ietf.org/html/draft-ietf-quic-tls-24#section-5.4.4,
	// initializes the ChaCha20 counter with "4 bytes of [...] sampled
	// ciphertext", so it's possible to have any counter value in [0, 2^32-1]
	// and attempt to encrypt one block.

	c, _ := NewUnauthenticatedCipher(key[:], nonce[:])
	c.Advance(0xffffffff)
	c.XORKeyStream(block[:], block[:])
}
```

Test output:
```
=== RUN   TestIETFQUICHeaderProtection
--- FAIL: TestIETFQUICHeaderProtection (0.00s)
panic: chacha20: counter overflow [recovered]
	panic: chacha20: counter overflow

goroutine 7 [running]:
testing.tRunner.func1(0xc000094100)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x1117de0, 0x1187e80)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
golang.org/x/crypto/chacha20.(*Cipher).XORKeyStream(0xc000034eb0, 0xc000034e70, 0x40, 0x40, 0xc000034e70, 0x40, 0x40)
	.../gopath/src/golang.org/x/crypto/chacha20/chacha_generic.go:206 +0x393
golang.org/x/crypto/chacha20.TestIETFQUICHeaderProtection(0xc000094100)
	.../gopath/src/golang.org/x/crypto/chacha20/chacha_test.go:38 +0x161
testing.tRunner(0xc000094100, 0x1169450)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
exit status 2
FAIL	golang.org/x/crypto/chacha20	0.274s
```

A panic with counter 2^31-1 and only 1 block to process is also present in the current `x/crypto/chacha20` and we first encountered it in a fork of `x/crypto/internal/chacha20` which exposed an API to set the counter in order to implement this aspect of the QUIC spec.

More background in this issue: https://github.com/lucas-clemente/quic-go/issues/2326.

**Comment by lukechampine** [comment]
Could the fix be as simple as this?
```diff
-	if uint64(s.counter)+numBufs*blocksPerBuf >= 1<<32 {
+	if uint64(s.counter)+numBufs*blocksPerBuf > 1<<32 {
```
That said, this feels like a separate issue -- the panic is coming from XORKeyStream, not Advance. I can open a separate CL for it if you'd like.

**Comment by rod-hynes** [comment]
> I can open a separate CL for it if you'd like

Yes, we'd appreciate that. We've hit this panic in production. Once `quic-go` is modified to use `x/crypto/chacha20` with Advance in place of its `x/crypto/internal/chacha20` fork, I expect we'll hit that panic again.

> Could the fix be as simple as this?

With that diff applied to `eef4af8e` the test case above still panics, but now at chacha_generic.go:308, where there's an additional overflow check:

```
		s.counter += 1
		if s.counter == 0 {
			panic("chacha20: internal error: counter overflow")
		}
```

We have a provisional fix here, which makes more changes. It leaves `counter` as a uint32 and adds an overflow flag which is used to defer the panic until 1 block _after_ the counter being 2^32-1: https://github.com/Psiphon-Labs/chacha20/commit/899a4be528633ecf678f45e4f6b177d0f89b9e7c. This fix is applied to a fork of the older `x/crypto/internal/chacha20`, not the current public package or this PR.

This fix works, and all test vectors pass. But we remain unsure whether there's some deliberate reason that the original code didn't want to process 1 block with the counter at 2^32-1 -- perhaps some other aspect of the crypto wouldn't work out right. So I'm not yet fully confident about our fix.

**Comment by lukechampine** [comment]
@rod-hynes I just pushed a fix here, try it out: https://github.com/lukechampine/crypto/commit/138d644a26872ddae52f188e43cd80749ecdd100
Will send a CL after this one is merged.

**Comment by rod-hynes** [comment]
Thanks. I can confirm that https://github.com/lukechampine/crypto/commit/138d644a26872ddae52f188e43cd80749ecdd100 fixes the TestIETFQUICHeaderProtection test case.

Also, it correctly panics when attempting to encrypt more than one block when the counter starting at 2^32-1.

However, changing the type of `counter` results in compile errors on platforms with asm code. E.g.,

```
$ GOARCH=arm64 go test -v
# golang.org/x/crypto/chacha20 [golang.org/x/crypto/chacha20.test]
./chacha_arm64.go:16:45: cannot use &c.counter (type *uint64) as type *uint32 in argument to xorKeyStreamVX
FAIL	golang.org/x/crypto/chacha20 [build failed]

```

This asm code for several platforms is the main reason why we implemented our fix that kept `counter` as a uint32.

**Comment by lukechampine** [comment]
Ah, I see. Okay, I've switched my patch to use the `overflow` bool strategy employed in your fork: https://github.com/lukechampine/crypto/commit/d3e589b4e01df3bbbbfde424de7fcc0b607f6636
Should work on all archs now.

**Comment by rod-hynes** [comment]
Thanks again. I pulled and ran the tests (success), and skimmed the changes. Looks good to me. I believe TestLastBlock covers our panicking QUIC case.

**Comment by FiloSottile** [comment]
FYI folks, we _do not_ monitor comments on GitHub PRs.

> Please don’t reply on this GitHub thread. Visit golang.org/cl/206638.

Please open an issue about this, and then feel free to send a CL fixing it.

**Pull request closed without merging**
