### PR TITLE
Lack of support for Keccak hashing algorith

### PR DESCRIPTION
**Pull request by r8d8**
Current implementation lack of KECCAK hash function 
Related to https://github.com/golang/go/issues/19709

### CODE REVIEW

**Comment by leonklingele** [comment]
@r8d8 have you tried submitting this patch to https://go-review.googlesource.com/?

**Comment by jgillich** [comment]
+1 @r8d8 Please? :) This would be great to have.

**Comment by andybons** [comment]
Hey @r8d8 we just need you to sign the CLA and we can start review. Thanks!

**Comment by leonklingele** [comment]
As @r8d8 did not respond within three months, I've created #41.

**Pull request closed without merging**
